### ISSUE TITLE
Light-weight timeout

### ISSUE THREAD

**Issue by repeatedly** [fluent-plugins-nursery/fluent-plugin-map#26]
#### Problem

This is performance improvement proposal.

Current implementation uses `Timeout::timeout`: https://github.com/fluent-plugins-nursery/fluent-plugin-map/blob/b2048ceeac5a58fd6dc8bcbb6f59a3f03e56f6a2/lib/fluent/plugin/map_support.rb#L106
`Timeout::timeout` is too slow because it launches one Thread per block.
In fluentd core, we implement light-weight timeout for parser plugin.
I think map plugin also uses this approach.

Here is benchmark:

```
require 'benchmark'
require 'benchmark/ips'

require 'timeout'
require_relative 'lib/fluent/plugin/parser'

checker = Fluent::Plugin::Parser::TimeoutChecker.new(10)
checker.start

def f
  nil
end

Benchmark.ips do |x|
  x.report "timeout" do
    Timeout::timeout(10) {
      f
    }
  end

  x.report "checker" do
    checker.execute {
      f
    }
  end
end

# result 
Warming up --------------------------------------
             timeout     5.279k i/100ms
             checker    67.093k i/100ms
Calculating -------------------------------------
             timeout     54.950k (± 3.1%) i/s -    279.787k in   5.096866s
             checker    818.054k (± 1.9%) i/s -      4.093M in   5.004828s

Comparison:
             checker:   818053.9 i/s
             timeout:    54949.9 i/s - 14.89x  slower
```

#### Steps to replicate

Don't depend on configuration

#### Expected Behavior

More better performance

#### Your environment

* OS version: All OS
* All fluentd version
* Latest version
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock

**Comment by cosmo0920** [comment]
I'll implement this.
